### ISSUE TITLE
Play Button Box

### ISSUE THREAD

**Issue by Imiona** [Jonius7/SteamUI-OldGlory#1]
Hi

With the newest release my Playtime Bar moved up to the Game Background. How can i revert this to look normal again?

Thx

![bar](https://user-images.githubusercontent.com/11210717/93526321-949c2500-f937-11ea-8cfc-129100da216b.png)

**Comment by Jonius7** [comment]
You can simply comment out the code in `libraryroot.custom.css` below and above the PLAY BAR comment tags. That is, add /* and */ like this:


`/* PLAY BAR LAYOUT - BETA */
/*`

and

`*/
/* END PLAY BAR LAYOUT */`

In the future I'll be creating a GUI App so you won't have to comment out CSS manually and can select what options you want with checkboxes

**Comment by Imiona** [comment]
Thx :)
