### ISSUE TITLE
How to get top bar like the first image shown in your gif?

### ISSUE THREAD

**Issue by ZachFett** [Jonius7/SteamUI-OldGlory#100]
At the start of the page a gif is shown with various improvements/options shown, and this is the first image in that gif:
<img width="1102" alt="chrome_09-21-2023_21-45-25" src="https://github.com/Jonius7/SteamUI-OldGlory/assets/29797689/0da29c06-60e4-4a10-bea6-c7a473fa4511">
I tried just about every setting I could think of but I couldn't get my top navbar to look like yours did here. It looks very similar to what the now-defunct "Metro for Steam" skin had, especially the placement of the download and friends list buttons. Is this still possible to do?

**Comment by Jonius7** [comment]
Correct, the top navbar is part of the now defunct "Metro for Steam" skin

Shiina did release a Metro skin that works with current Steam updates here: https://github.com/AikoMidori/SteamSkins

It should be possible to integrate the new Metro skin into OldGlory

**Comment by Jonius7** [comment]
I have released [5.12.1](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.12.1) 
the Metro skin style top bar is available at **CSS Options** -> **CSS Sections** ->**module_metro_topbar**

**Comment by ZachFett** [comment]
Thank you very much! I wasn't aware of Shiina's Metro skin, and I really appreciate you adding this option too!
