### ISSUE TITLE
New Steam Client the dim non installed games not working

### ISSUE THREAD

**Issue by molitar** [Jonius7/SteamUI-OldGlory#101]
It seems the JS commands are not working for example What's New won't show up at bottom and dim Non-Installed Games also not working.  How to fix this?

**Comment by Jonius7** [comment]
Did you get it working? It still seems to be working for me (with reinstalling Steam over the top)

**Comment by molitar** [comment]
I finally got it working.  It took me several steps though to get it to work.

Run Steam verify files and let it replace all files.
OldGlory was not detecting update to latest release so I had to delete the old and download the latest extract and than run the patch on it.

now even though I am using this for my target with switches I still get message the folder is unwriteable and wants me to run repair on it from Steam.

"C:\Program Files (x86)\Steam\steam.exe" -noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl

Am I missing a switch or using a wrong switch?
