### ISSUE TITLE
install script requires both python-jsbeautify and js-beautifier which are in conflict with eachother

### ISSUE THREAD

**Issue by NilTPL** [Jonius7/SteamUI-OldGlory#102]
i can't use the install script without having both those packages installed, but i cant install both of them at once

distro: arch linux
package manager: pacman
aur helper: yay

**Comment by Jonius7** [comment]
OldGlory should only need [`jsbeautifier`](https://pypi.org/project/jsbeautifier/) not sure what `python-jsbeautify` is

**Comment by NilTPL** [comment]
![image](https://github.com/Jonius7/SteamUI-OldGlory/assets/76227208/ef95ceee-2f75-4fd8-8acc-f003a9624a8a)
either way, this is what i get running 
python old_glory.py

**Comment by Jonius7** [comment]
Since [5.12](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.12), you'll also need to install Rust.
I'll try settting up a Linux Virtual Machine so I can inform you of further steps you need to take.

**Comment by Jonius7** [comment]
I have added some details to the Linux page in the Wiki: https://github.com/Jonius7/SteamUI-OldGlory/wiki/Linux

I have successfully got it running in Linux Mint, though with the following error: https://imgur.com/a/3eZsXVb

This means CSS tweaks are working, but JS tweaks aren't.

**Comment by NilTPL** [comment]
Thanks,

although building this on arch is a pain, you might want somebody to look into that

**Comment by Jonius7** [comment]
> I have successfully got it running in Linux Mint, though with the following error: https://imgur.com/a/3eZsXVb
> 
> This means CSS tweaks are working, but JS tweaks aren't.

Turns out `fixes.txt` had CRLF line endings (from Windows), converting the file to use LF line endings fixed the error.
