### ISSUE TITLE
Cant install 'jsbeautifier' and 'js_beautify' at the same time

### ISSUE THREAD

**Issue by mr-sihc** [Jonius7/SteamUI-OldGlory#104]
ARCH LINUX

These packages conflict...

I get
`ModuleNotFoundError: No module named 'js_beautify'`
or
`ModuleNotFoundError: No module named 'jsbeautifier'`

any help?

**Comment by NilTPL** [comment]
I've already asked this question, the dev has answered

![image](https://github.com/Jonius7/SteamUI-OldGlory/assets/76227208/6d589df7-a355-41f4-932e-a8a36b8ecf56)
You need to `cd` into the cloned git repo, then create a virtualenv and run `maturin develop`

**Comment by mr-sihc** [comment]
i did and i cant run it in the venv...
how??

**Comment by NilTPL** [comment]
idk i did this with the help of the arch linux discord
here's the link https://discord.com/channels/399812551963049995/1167143382053834782

it might help you

**Comment by Jonius7** [comment]
#102
