### ISSUE TITLE
SKINS FOLDER, tthen OLD GLORY FOLDER WITH SKINS.json

### ISSUE THREAD

**Issue by madmaxgrey** [Jonius7/SteamUI-OldGlory#106]
the way your applying this shit is stupid to be blatant, it should be a on and off not just take over the entire setup when you have a patcher running you expect to be able to swap skins without conflict,

recreate the installer and turn it into a configuration creator then have it make a old glory folder in the steam-ui/skins folder with a skins.json so you can turn it on and off

**Comment by PhantomGamers** [comment]
Strange that I don't see a pull request linked to this issue with how rude your message was. If it's so stupid, maybe you should fix it.

**Comment by Jonius7** [comment]
If 6.0 ever comes out, a rework might be necessary. But SteamUI-OldGlory has been designed to be independent of other patchers (and would run beside SFP)

**Comment by Jonius7** [comment]
I have deleted the `millennium` subfolder and am releasing 5.14 where you can now select the Install Location for OldGlory CSS files - in Advanced Options select the Millennium option and OldGlory will install to `steamui\skins\OldGlory`

**Comment by Jonius7** [comment]
In [5.15](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.15), SteamUI-OldGlory now installs to `steamui\skins\OldGlory` by default.
