### ISSUE TITLE
Old Glory mostly broken as of latest update

### ISSUE THREAD

**Issue by FatheredPuma81** [Jonius7/SteamUI-OldGlory#108]
It looks like something changed and now everything EXCEPT friends is broken.

**Comment by Jonius7** [comment]
Yes this has been expected for a while, as seen here:
https://steamcommunity.com/groups/SteamClientBeta/discussions/3/4298194722189670859/

I have updated the CSS classes in the `scss` folder on `dev` branch, you can copy and paste that folder into your OldGlory installation and see how that works, I will be doing testing on it later today.

**Comment by Jonius7** [comment]
I have pushed out a new release ([5.13](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.13)) where it looks like things are working. Some small things may be missing upon further inspection.
