### ISSUE TITLE
Quick question - is it possible to open "show more details" by default?

### ISSUE THREAD

**Issue by Kraahkan** [Jonius7/SteamUI-OldGlory#12]
I might have a poke around the css / js to figure it out myself but just wanted to know if it's even possible :)

thx

**Comment by Jonius7** [comment]
So, for CSS
`.appdetailsgameinfocontainer_AppGameInfoContainer_25oBZ.appdetailsgameinfocontainer_AppDetailsCollapsed_3yfoe.appdetailsgameinfocontainer_Glassy_2QAgO {
    height: 170px !important;
}`

will force the collapsed "Show more details" panel to show up (height 170px), but it is dimmed.

It's likely possible to change the default behaviour but I'll have to find the right JavaScript code to tweak.

**Comment by Jonius7** [comment]
I have found it.
Option is added in new version of `fixes.txt` under **Expand Show more Details panel by default**
`old_glory` will download it as part of a "small update"

---
This made me realise I could be programming the reading of config much better as the `fixes.txt` comes with a certain set configuration. Note to fix in 6.0 (if I get around to doing it)

**Comment by Kraahkan** [comment]
Wooo, it works! Well I had to fiddle around with the config for some reason. might have been user error on my part, but simply installing it after getting the update didn't apply it. Oh well it works now, and looks GREAT :) thx so much

**Comment by Jonius7** [comment]
> Well I had to fiddle around with the config for some reason.

This is expected atm for safety reasons, sometimes you need to check and uncheck a JS option to get it to reinstall the JS with the new options.
