### ISSUE TITLE
Game pictures getting cut-off  at the bottom.

### ISSUE THREAD

**Issue by Rex117** [Jonius7/SteamUI-OldGlory#14]
Hey there, I am having an issue where the Library horizontal game pictures are getting cut-off when reaching the bottom. How or where should I go to fix this?

![steam_library_issue](https://user-images.githubusercontent.com/52544680/110154825-b89ed600-7db2-11eb-8ef2-220f30f20862.JPG)

**Comment by Jonius7** [comment]
You mention in #6 that you were using an earlier version. Is it still showing up for you?

Firstly, I would grab the current version of some .scss files, namely `_home_collections.scss` and replace in the `OldGlory/scss` directory. **Install** and see if that works.
Then, I would go ahead and click the Remake JS button.

**Comment by Rex117** [comment]
Hey @Jonius7 thanks for replying and sorry if it seemed like I was spamming the chats, I just don't know if you get a notification when someone comments or when a new thread is created. After reading your posts it made me realize that I had just updated my Steam, from the other solution I was using, and there might have been leftover files. I was using youtuber Leeson's solution: [https://www.youtube.com/watch?v=knIfk_-YOS8](url). I proceeded to re-install Steam and used your video to redo the whole process again from the beginning, which ended with the same result. I then replaced just the `_home_collections.scss` which resulted in errors to which I just deleted the SteamUI-OldGlory-Release_5.5.3 folder, re-extracted it again and replaced the files in the scss folder with the ones from the SteamUI-OldGlory-master folder. This did not fix the issue either, I am not completely clueless when it comes to programming, I just mainly use Python and my JavaScript is almost non-existent. Therefore, if the I have to modify a file to solve this I can, I just can't make sense of all these files.

**Comment by Jonius7** [comment]
Ok, I might see a problem.

Are you using Compact (8px 5px) or Default (24px 16px) spacing in CSS Options?

**Comment by Rex117** [comment]
@Jonius7 you solved it. After unchecking the **Home Page Grid Spacing** in JS options and Installing it everything looks perfect. Thank you very much!!!!  :D

**Comment by Jonius7** [comment]
For future reference, the "corresponding JavaScript values are these ones in `fixes.txt`
![2021-03-29 08_29_50-D__New Horizons_Hearthstone_SteamUI-OldGlory_fixes txt - Notepad++](https://user-images.githubusercontent.com/1049415/112770237-1698a380-9069-11eb-9df8-457f35e67412.png)
