### ISSUE TITLE
Re-minify JS file not finishing

### ISSUE THREAD

**Issue by sctanf** [Jonius7/SteamUI-OldGlory#15]
Whenever the JS minify runs, OldGlory uses up my cpu and never finishes.

**Comment by Jonius7** [comment]
Firstly, run Remake JS under the Settings button and tell me if that works.
Just to clarify, OldGlory is getting stuck at `Re-minify JS file`? 

I encountered this issue a while back where it was not copying files properly on clean installs, and fixed it in [5.0.1](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.0.1)
Though it's possible it could reappear some other way.

Are any errors popping up in the text output?

**Comment by sctanf** [comment]
Yes, either when pressing "install" after changing JS options or pressing "remake JS" leads to getting stuck at "Re-minify JS file." There are no errors in the output, however attempting to close OldGlory while it was stuck closes the window but doesn't end the process, it has to be closed in the task manager.

**Comment by sctanf** [comment]
Ok thanks, I will give this a try.

I am the main user, with admin permissions.

**Comment by sctanf** [comment]
I tested with and without admin permissions, it still appears to be stuck at Re-minify JS file after a few minutes.
I should add that the CSS has been working fine, if that is important.

**Comment by Jonius7** [comment]
And no error?

Can you check if `fixes.txt` and `libraryreet.js` are in the OldGlory directory, and also in the `steamui` directory?
- There are buttons under the Advanced Options tab to quickly get you there.

If not, the workaround is to copy them over manually to the `steamui`

**Comment by sctanf** [comment]
fixes.txt is in both directories.
libraryreet.js is not in the OldGlory directory and is present as a 0KB file in the steamui directory.
I've only waited ~3 minutes before concluding it's stuck.
Log:
Running js_tweaker
Opening JS file and beautifying...
Writing beautified file... please do not close
Beautified file write finished
library.js changing to use tweaked JS.
Finding Fixes...

FIX: }, e.m_nScrollTop = 30, e.m_elTarget = D.createRef(), e
FIX: var timeSince;t=this.m_elGrid.current.getBoundingClientRect(),timeSince=performance.now()-this.lastTime,this.lastTime=performance.now(),console.log(timeSince),setTimeout(function(){timeSince>60&&(console.log("ACTUALLY COMPUTING LAYOUT"),this.ComputeLayout())}.bind(this),200); /*this.props.maxRows < 2 || (t = this.m_elGrid.current.getBoundingClientRect(), n = Math.abs(t.top - this.m_fLastScrollTop), this.props.childHeight * this.props.scaleGridItems / 8 < n && (this.m_fLastScrollTop = t.top, t.top < window.innerHeight && 0 < t.bottom && this.ComputeLayout()))
FIX: */}, e.prototype.OnRestoreScroll = function() {
FIX: t = t.slice(0, 12),
FIX: var e = this.props.details.vecScreenShots.slice(0, 9).map(function(e) {
FIX: return 1 == (e = ro.GetComputedDisplaySize(e)) ? (n = 120, r = !0) : 2 == e ? n = 160 : 3 == e && (n = 200), {
FIX: }(n), jm.Initialize(t), this.SetStateLoaded(),document.getElementsByClassName('smartscrollcontainer_Body_3lDcz')[0].scrollTop = 30, [3, 9];
FIX: /*for (var n = [], r = 2; r < arguments.length; r++) n[r - 2] = arguments[r];

Re-minify JS file

**Comment by Jonius7** [comment]
Issue has been identified. Sorry it took so long. The problem is with the `Change Game Image Grid Sizes` option, the other options work fine.

Quick fix will be out later today.

**Comment by sctanf** [comment]
Re-minify JS is finishing and the tweaks are applied properly, thank you!
