### ISSUE TITLE
Not working for me at all

### ISSUE THREAD

**Issue by molitar** [Jonius7/SteamUI-OldGlory#16]
I got the friendspatcher running.

I downloaded 5.5.3 and let it update.  I than only checked option for the vertical game images and install.  The images DO NOT Change they are still awful portrait.

**Comment by Jonius7** [comment]
It seems there's a new Steam Client update. I'll have a look.

**Comment by Jonius7** [comment]
New `fixes.txt` has been pushed out for the JS tweaks. The OldGlory app should prompt to download it on launch.

**Comment by Jonius7** [comment]
Closing this issue as it should be the same one as in #15 
If not, the issue can be re-opened.
