### ISSUE TITLE
Hover issue

### ISSUE THREAD

**Issue by Kraahkan** [Jonius7/SteamUI-OldGlory#18]
![image](https://user-images.githubusercontent.com/8085764/120049371-94781d00-bfce-11eb-9c50-59447af08f93.png)

Weird issue on hover.. I seem to remember it working before.

If you can't fix this, could you clue me into the css selector? There's no chrome dev tools so I dont' know how to select it lol. I'll just hide it if it can't be fixed.

Thx very much, your app is a must have

**Comment by Jonius7** [comment]
This is how you can use Chrome Dev Tools with Steam:
https://github.com/Jonius7/SteamUI-OldGlory#debugging-steam-library-yourself

To catch the Hover div you need to set the div to break on `subtree modifications`
https://imgur.com/a/g9ZIzts

The class in question is `.hoverposition_HoverPosition_3vg1v .hoverposition_Ready_1Ye_0`

**Comment by Kraahkan** [comment]
I'm not running the shiina one, it's the second theme (dark library).

I tried fiddling around with the css files but I'm not sure where to insert my custom code. I'm ok living with the bug tbh, it's not a big deal considering how much better steam looks with your mod

**Comment by Jonius7** [comment]
I have noticed a similar visual bug where the hover looks transparent but with steam-library. It seems to fix itself after switching between themes (or End Task on `Steam Client WebHelper` in Task Manager)

As for where to put your custom code, in the `scss` folder, use the `_user_module1.scss` and `_user_module2.scss` files. All the other `.scss` files are split by section, and `libraryroot.custom.scss` imports them

**Comment by Kraahkan** [comment]
Hmm I'm not 100% sure the bug is with your app actually. It may be a steam
wide problem because I tried your code and it didn't work. Also, when
switching to the default skin the bug still persists.

-

+1 (250) 299-2742 | ***@***.***
Website*: **I make beautiful websites.* <https://jdlindsay.com>

**Comment by Jonius7** [comment]
Closed, unsure of issue with Steam
