### ISSUE TITLE
[Bug] Missing buttons using OldGlory Tweaks GUI

### ISSUE THREAD

**Issue by CrazyGunman2C4U** [Jonius7/SteamUI-OldGlory#2]
Good day,

just today I found your program and it left an excellent impression. I appreciate all the work you've invested!

However, when starting 'old_glory.exe' I noticed that I can (de-)select the checkboxes, but the buttons for CSS / JS Options; Install, Reload Config and the settings icon are missing.

On first startup, it reports that 'oldglory_config.cfg' is being generated, which is correctly detected after a restart. Yet the checkboxes are not saved and the buttons remain invisible.

![GUI](https://user-images.githubusercontent.com/53367662/101984981-b67a1f00-3c7c-11eb-9bde-37a508b084eb.png)

There also seems to be a problem with the 'Crisp Cut' theme, but since I haven't been able to apply it yet, I don't know whether this is a separate issue.

I have tried the following without success:
- disabling firewall / hosts / custom DNS to make sure nothing needs to reload.
- using a path without spaces
- putting the zip for the patcher and OldGlory in Downloads, Appdata and C:\ root folder
- on 2 computers with Windows 8.1 and Windows 10 LTSC

Otherwise, I don't know what else it could be.
I also deleted the 'steamui' folder and regenerated it.
[Steam is installed on my computer under 'D:\Software\Steam'].

The patcher itself works great even after applying the new steam beta update.

**Comment by Jonius7** [comment]
Crisp Cut theme is not fully implemented. It will be in a future update. (That's my bad for not understanding that the exe built with a more recent version than I intended)

With the buttons at the bottom missing, this looks like the border thickness is cutting into the window dimensions, as on my system, there is no window border.

I'll make the window size bigger to give it more breathing room. Additionally I'll also make the window resizable (up to the screen dimensions).

Go ahead and try this build (put it in the folder with the other files), see
[old_glory_pre_4.0.3.zip](https://github.com/Jonius7/SteamUI-OldGlory/files/5683406/old_glory_pre_4.0.3.zip)
 if you can see the buttons now.

**Comment by CrazyGunman2C4U** [comment]
It works wonderfully, thank you!

[4.0.3 looks like this now.](https://user-images.githubusercontent.com/53367662/101990344-5eecab00-3c9e-11eb-8f50-623bd2f03206.png) The buttons are still slightly hidden, but [resizing works great and fixes it](https://user-images.githubusercontent.com/53367662/101990358-83488780-3c9e-11eb-9156-c81d396f98f6.png).

When maximizing, it used to [snap to the top-left corner](https://user-images.githubusercontent.com/53367662/101990376-a2471980-3c9e-11eb-839b-66c057381f82.png) of my screen.
4.0.3 fills it [entirely](https://user-images.githubusercontent.com/53367662/101990410-d8849900-3c9e-11eb-8be6-91ef37af00cb.png) as it should 👍

**Comment by Jonius7** [comment]
4.1 is out. If the buttons are still hidden by default, I'll slightly increase the window size again.

**Comment by CrazyGunman2C4U** [comment]
The update itself is great, it fixed several issues I was experiencing.
Yet the buttons are still partially hidden.

It looks like this on 4.1:
![issue](https://user-images.githubusercontent.com/53367662/102656383-b641be00-416b-11eb-924b-553c34b06d25.png)

**Comment by Jonius7** [comment]
Do you happen to be on 125% font scaling? The font seems to be filling the windows more on your screen.

**Comment by CrazyGunman2C4U** [comment]
Yes, I've set it to 125% on both [Windows 8](https://user-images.githubusercontent.com/53367662/102686317-c8a90f80-41de-11eb-89e4-6317ab8f4269.png) and [Windows 10](https://user-images.githubusercontent.com/53367662/102686330-d6f72b80-41de-11eb-8bda-4611d855bce6.png). I completely forgot about that, since I usually only change it during initial setup.
Sorry for causing any trouble.

**Comment by Jonius7** [comment]
I have figured out the issue, the GUI app scaling will now stay fixed, and will work at 125% scaling with the next update.
