### ISSUE TITLE
Vertical Nav Bar hiding items into overflow menu

### ISSUE THREAD

**Issue by Braden123135** [Jonius7/SteamUI-OldGlory#20]
When using the vertical nav bar option, my steam is hiding all items except for "Store Page" this seems like steam is trying to display the nav bar horizontally and creates an overflow menu for all items that don't fit horizontally. Heres an image of the issue 
<img width="151" alt="VerticalNavBar" src="https://user-images.githubusercontent.com/17503813/120928132-06282900-c6a9-11eb-96e9-ed32b0d249b8.PNG">

[Imgur](https://imgur.com/a/hfeZEXp)

The issue also occurs if "Classic layout" option is disabled.

**Comment by Jonius7** [comment]
Should be fixed with [`d9f680`](https://github.com/Jonius7/SteamUI-OldGlory/commit/d9f6801c0b8ec8cdd4c8325c636312f2f2757ca4)

OldGlory will prompt you to download the new version of `fixes.txt`

**Comment by Jonius7** [comment]
I am not sure on that, but the latest beta version is taken from `dev` branch. I have not tested out the current state of `master` branch if you're running from the `.py` files instead of the `.exe`

**Comment by Jonius7** [comment]
Fixed finalised in [Release 5.7.1.1](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.7.1.1)
If the problem appears again similarly in the future, create a new issue.

**Comment by Potato95** [comment]
Having the same problem today using Release 5.7.4.2

![image](https://user-images.githubusercontent.com/46279408/147887312-b30e3023-7f17-4b21-9d08-bbac76ae70e4.png)
