### ISSUE TITLE
Installing Unticked Options

### ISSUE THREAD

**Issue by willowFins** [Jonius7/SteamUI-OldGlory#22]
I have options such as the box play button and vertical navbar unticked as I want to use Old Glory mainly to rid of the whats new section, but Old Glory installs these options anyways.

**Comment by Jonius7** [comment]
Check to see if the options are working as intended in the newest release: https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.7.1.1

**Comment by willowFins** [comment]
Newest release fixed the box play button and vertical navbar being applied even though unticked, but the changes on the left side games list still apply even though I have 0 of those options applied.

**Comment by Jonius7** [comment]
Can you be more specific? There are additional options on the CSS Options -> Quick CSS page

Individual parts of the CSS tweaks can be enabled/disabled like this: http://imgur.com/a/PocNfPE

**Comment by willowFins** [comment]
Thank you so much!
Editing the SCSS file like pictured works just as I want.

Sorry for the troubles!
