### ISSUE TITLE
Broken features

### ISSUE THREAD

**Issue by ong-yinggao98** [Jonius7/SteamUI-OldGlory#23]
Steam reset the Library GUI again so I ran SteamFriendsPatcher again and somewhat restored it but now the vertical nav bar is broken again (v5.7.1.1):
![image](https://user-images.githubusercontent.com/52755148/126058505-1a4139c8-0bd1-41e1-b3d1-2cab1686959f.png)

Unchecking a feature such as "Classic Layout" causes the library to go black permanently as soon as you click on a game's page, and upon restarting it resets Steam to before SteamFriendsPatcher was used.

**Comment by eyedine2** [comment]
you need to remake the JS, it gets reset every time the steam client updates. It's in the options (cog) menu.
