### ISSUE TITLE
Sticky image spillover Broken on July 30th beta

### ISSUE THREAD

**Issue by eyedine2** [Jonius7/SteamUI-OldGlory#24]
> libraryreet.js:891 FAILED TO INITIALIZE THE CLIENT TypeError: Cannot read property 'nAppId' of undefined

this error appears in the chrome console when remaking js with sticky image spillover active

**Comment by Jonius7** [comment]
Noted. Some JS tweaks require maintenance between each update and have been broken for a while so I am looking to rework that.

**Comment by Jonius7** [comment]
Option is now fixed on Steam Beta with Release 5.7.3.
https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.7.3

I will leave this issue open for a little while as another Steam update could require me to update it again. 
Until I get the JS Tweaks rework done.
