### ISSUE TITLE
linux/deck support?

### ISSUE THREAD

**Issue by MissLavender-LQ** [Jonius7/SteamUI-OldGlory#28]
with the steam deck coming out soon it would be nice to have Linux support for the desktop docked mode as well as just general Linux support and if you programs UI is cross platform like gtk, java gui, qt or python gui as well if steam is layed out in a way that isn't to different the the windows version it shouldn't take to much to translate it and i mean if u don't wanna port it out right maybe a way to run it in wine (already tested it doesn't seem to understand the differences in file system. maybe an option to manually pick a file location would fix this)
either way if you need some to for testing email me at misslav@protonmail.com

**Comment by Jonius7** [comment]
OldGlory is written in python so you can run the `.py` files directly by downloading the source code, Wine isn't needed.

The only part is patching the CSS, which through [SteamFriendsPatcher](https://github.com/PhantomGamers/SteamFriendsPatcher) is Windows only, so manually patching it will be needed.

I may write some code to support CSS Patching within OldGlory in the future.

There are details here on how to Run on Linux: https://github.com/Jonius7/SteamUI-OldGlory/wiki/Linux

**Comment by MissLav** [comment]
oh ty for the quick response sorry i dont check github to much ill leave this tab open so i remember to do it

**Comment by Jonius7** [comment]
Information on getting OldGlory to run in Linux is here: 
https://github.com/Jonius7/SteamUI-OldGlory/wiki/Linux
