### ISSUE TITLE
Steam takes ages to start

### ISSUE THREAD

**Issue by 1S7R1K3R** [Jonius7/SteamUI-OldGlory#29]
hello, i'm new here.
i did everything like the yt-video but after i restart steam it takes ages to start again.
it's stuck in "updating steam - extrackting package" until i close "SteamFriendsPatcher"

is there a fix?

**Comment by Jonius7** [comment]
I do not know about your specific issue, are you saying it works until you restart Steam?

I have identified a different issue that is related to #15 and #27, a hotfix will be out soon.

**Comment by 1S7R1K3R** [comment]
Looks like it's stuck in "updating steam" until i stop the Scan of SteamFriendsPatcher. 
After i stop it manually, steam started normally.

**Comment by PhantomGamers** [comment]
> Looks like it's stuck in "updating steam" until i stop the Scan of SteamFriendsPatcher. After i stop it manually, steam started normally.

This is something you should report over on the SFP repo then, make sure to include which version of the patcher you are using if you do open an issue over there.
