### ISSUE TITLE
how do i uninstall?

### ISSUE THREAD

**Issue by Kraahkan** [Jonius7/SteamUI-OldGlory#3]

**Comment by Kraahkan** [comment]
i like it but for some reason all my uninstalled games are faded out. really annoying

**Comment by Jonius7** [comment]
If you want to change that, for now, in `libraryroot.custom.css`, you want to change the value of 
--UninstalledGameImageOpacity: 0.5;
to --UninstalledGameImageOpacity: 1;

Then, in the app, hit `Reload Config` and `Install`

**Comment by Kraahkan** [comment]
thank you! recent games looks weird and is cut off, but i deleted it and everything else looks awesome

**Comment by Jonius7** [comment]
Shelve heights fixed for both portrait (default) and landscape images in [4.1](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_4.1)

**Comment by Kraahkan** [comment]
Looks great!
