### ISSUE TITLE
Any way to fix this? Overlay appears with that "expand more details" checked.

### ISSUE THREAD

**Issue by Kraahkan** [Jonius7/SteamUI-OldGlory#32]
![image](https://user-images.githubusercontent.com/8085764/145484245-a26acd36-664a-4817-a612-12e18282337c.png)

 I tried fiddling around with the JS in fixes.txt but I don't see any parameters relating to opacity

**Comment by Jonius7** [comment]
the shadow is due to the `**.*.GameInfoShadow` slement, where * are A-Z random letters that change with each update
901a44f2de1ee016c84cf3b43b89a1511a22d765
