### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by adrian5683** [Jonius7/SteamUI-OldGlory#33]
Hi, I'm encountering an error whenever I try to install the css tweaks:

~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "backend.py", line 847, in write_js_fixes
PermissionError: [Errno 13] Permission denied: 'fixes.temp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manager.py", line 55, in install_click
  File "backend.py", line 907, in write_js_fixes
UnboundLocalError: local variable 'line' referenced before assignment
~~~~~~~~~~~~~~~~~~~~

I tried all of the steps in the troubleshooting section and the same error occurs, hope you can help. I only have Install CSS Tweaks selected and have Steam Beta Update enabled.

**Comment by PhantomGamers** [comment]
Try running the program as admin, or move it to a folder that you have write permissions for

**Comment by adrian5683** [comment]
Thanks, it finally worked when I moved it inside the Steam folder.
