### ISSUE TITLE
Vertical Nav Bar overflow menu

### ISSUE THREAD

**Issue by Potato95** [Jonius7/SteamUI-OldGlory#34]
Vertical Nav Bar overflow menu using Release 5.7.4.2

![image](https://user-images.githubusercontent.com/46279408/147887849-26fd4865-1b0f-46be-8d32-336883274f2f.png)

**Comment by fuzzywavecode** [comment]
Having the same issue.

**Comment by Jonius7** [comment]
Fixed until next Steam update
fb7552b40544580a758f7e45888c2efb357124e6
