### ISSUE TITLE
Skin doesn't apply to the Steam Friends Tab?

### ISSUE THREAD

**Issue by MeatyChan** [Jonius7/SteamUI-OldGlory#36]
I got the skin to work, but does it not apply to the Friends Tab? I was really hoping it would be changed like everything else..

**Comment by Jonius7** [comment]
SteamUI-OldGlory only does library tweaks.
Have a look at this guide for some friends skins: https://steamcommunity.com/sharedfiles/filedetails/?id=1941650801
