### ISSUE TITLE
Show only header images on game hover instead of screenshots?

### ISSUE THREAD

**Issue by Kennyluzz** [Jonius7/SteamUI-OldGlory#37]
I would love an option to show just the header ("landscape") images when hovering over a game, instead of having it do a screenshot slideshow. I hope you can consider this. 
Apologies if this is not the right place for suggestions.

**Comment by Jonius7** [comment]
This has been added under a new option: `Disable screenshot slideshow on hover`
b09868ac4ee0f27fffb483825840157376d916ee
