### ISSUE TITLE
[Bug] Misaligned friends icons in the 'Recent Games' shelf

### ISSUE THREAD

**Issue by CrazyGunman2C4U** [Jonius7/SteamUI-OldGlory#4]
Likely related to:
```
Fixes
[...]
    (JS) (CSS) Fixes for Recent Games and Play Next shelf height, mainly when using landscape images
```

The friends UI which informs you who is currently playing does not account for the new vertical/landscape tiles.
![friends](https://user-images.githubusercontent.com/53367662/102657020-d1f99400-416c-11eb-9d8a-9ec2dc111714.png)

This might also apply to the 'Play Next' shelf, but I can't confirm that atm as none of my friends are playing the suggested games.

**Comment by Jonius7** [comment]
Looks like the Steam original has the friend hover stuck to a fixed size, I've made a few changes, try this file:

[libraryroot.custom.css 4.1.1-pre.zip](https://github.com/Jonius7/SteamUI-OldGlory/files/5718928/libraryroot.custom.css.4.1.1-pre.zip)


[Compare](https://github.com/Jonius7/SteamUI-OldGlory/compare/b6235e5...19870bf)

**Comment by CrazyGunman2C4U** [comment]
[Confirmed working!](https://user-images.githubusercontent.com/53367662/102686595-a7492300-41e0-11eb-92f7-5322ab7b130d.png)
![fixed](https://user-images.githubusercontent.com/53367662/102686613-b9c35c80-41e0-11eb-97ec-5381d5726b1a.png)
