### ISSUE TITLE
Library themes and patches not applying, SteamFriendsPatcher not giving 5.css/6.css

### ISSUE THREAD

**Issue by ToxxyTheTrash** [Jonius7/SteamUI-OldGlory#40]
Hi there. 
I've decided to update OldGlory as I was still on v5.7.4 and one of my themes was a bit broken. After updating I've started having problems with getting anything to patch. It's a bit hard to remember how exactly I got to this point but:
-OldGlory does not wanna apply Library themes nor patches.
-OldGlory keeps logging *5.css (previously known as libraryroot.css) not found* as SteamFriendsPatcher proceeds to never give me 5.css on Stable and 6.css on Beta.

- I've been troubleshooting this for the past hour and a half, retrying and seeing if changing to patch other css files (0.css, 1.css, 37.css(???) and library.css for example) wouldn't change anything but would only result in breaking the whole library's css, making me clear the steam cache within SteamFriendsPatcher. (screenshot showing me patching 6.css on stable, no 5.css present)
![image](https://user-images.githubusercontent.com/28952722/160787879-1d51c3f1-e89a-43a6-a40a-f83049da4b4f.png)
- I've tried remaking JS and resetting multiple times, when installing the css I would usually only get this as an output:
> Applying CSS settings...
> Settings applied.
> Config file written.
> Applying CSS Theme: Dark Library (Thespikedballofdoom)
> Loaded JSON data. (old_glory_data.json)
> Existing libraryroot.custom.css code detected.
> Backed up steamui/libraryroot.custom.css to steamui/libraryroot.custom.css.backup2
> File libraryroot.custom.css written to c:\program files (x86)\steam\steamui/libraryroot.custom.css

which makes me think it isn't really copying anything (could be entirely wrong), tried running as admin with no difference
- I've tried removing Steam Customizer to see if that was conflicting with no difference
- I've tried reverting to v5.7.4 to see if then anything would change, with no luck seeing it work
- I've tried downloading Steam's installer, hoping it would refresh some files, no luck once again

At this point I've ran out of ideas on what else to do aside from give up, as I seem to be missing something or Steam changed something.

I am currently on Stable and my OldGlory options are seemingly set to default with the Dark Library theme selected:
![image](https://user-images.githubusercontent.com/28952722/160786765-ec811209-d010-4547-983a-ee4a6f5d00f3.png)
![image](https://user-images.githubusercontent.com/28952722/160786799-79b06f1c-e7c0-4e10-9b69-ea68cdfca221.png)

If I've missed on providing any more info or if I should reinstall Steam entirely (as I've avoided doing that), let me know, thank you.

**Comment by ZeldrexK0DE** [comment]
same prob, just here for info

**Comment by AlVar009** [comment]
yup same issue

**Comment by AlVar009** [comment]
> yup same issue

hopefully they can fix this.

**Comment by AedraRising** [comment]
Okay, I'm glad that I'm not the only one who this latest update fucked with. Yeah, literally nothing about the program even functions now, no matter what you apply nothing ends up changing at all besides Steam reloading for a second.

**Comment by ZeldrexK0DE** [comment]
WHen devs don't respond

**Comment by AedraRising** [comment]
Oh wow, you weren't kidding. Like, I'd understand if they haven't fixed it by now because the solution might be a bit complex or whatever, but I don't know, I would prefer some sort of transparency of at least acknowledging the situation.

**Comment by itssomeone17** [comment]
Yeah, I noticed that, too, it's really annoying. My solution for now is to use the previous version, 5.7.4.2, and ignore the update prompt, which works perfectly fine. I just wish this would be fixed, though.

**Comment by ZeldrexK0DE** [comment]
> Yeah, I noticed that, too, it's really annoying. My solution for now is to use the previous version, 5.7.4.2, and ignore the update prompt, which works perfectly fine. I just wish this would be fixed, though.

How did u make it work with the older version. I think i've tried that too and it didn't work.

**Comment by ToxxyTheTrash** [comment]
> Yeah, I noticed that, too, it's really annoying. My solution for now is to use the previous version, 5.7.4.2, and ignore the update prompt, which works perfectly fine. I just wish this would be fixed, though.

I assume you still have the old files, which I don't anymore so I couldn't revert to an older version. But uh yeah this is taking a long while to get any attention from the devs, hoping something will come soon.

**Comment by Jonius7** [comment]
I've found the issue, for whatever reason, code that was working perfectly fine before just stopped working.

what was happening was the file `scss/libraryroot.custom.scss` was not writing the themes in properly and the file would get cleared, meaning no tweaks would get applied.

Sorry it has taken so long, I didn't pick up the bug initially because it would work perfectly fine if no theme was selected with a fresh installation.

**Comment by ZeldrexK0DE** [comment]
theres no errors but it still doesn't apply anything 
![image](https://user-images.githubusercontent.com/83987610/164944677-7efadb94-b7d9-48d9-a3e0-7c0afbbf4592.png)

**Comment by AlVar009** [comment]
the friends patcher is working now but not the theme. i can't get a custom theme to install

**Comment by ToxxyTheTrash** [comment]
Downloaded the new release, themes and addons get applied without issue!
![image](https://user-images.githubusercontent.com/28952722/164985320-bd00011e-1dcc-4b2d-8dcf-d861a4ca5fc9.png)
