### ISSUE TITLE
Error when installing tweaks (see image)

### ISSUE THREAD

**Issue by AlVar009** [Jonius7/SteamUI-OldGlory#41]
im getting an error when trying to install a custom theme its something to do with "manager.py" and "vertical nav bar" heres my settings i wanted to apply. i wanted to use the dark theme but no themes will apply

![image](https://user-images.githubusercontent.com/5095919/165084120-46d5edbb-bda2-49bb-a958-84b14abc9190.png)

**Comment by Jonius7** [comment]
For whatever reason, code that used to work is now printing extra new lines when updating small files such as `fixes.txt`

It should be fixed in the latest release (5.8.3)
