### ISSUE TITLE
The tool no longer works after todays steam update.

### ISSUE THREAD

**Issue by Lore-Soong** [Jonius7/SteamUI-OldGlory#44]
please help steam is so awful without the OldGlory tweaks

**Comment by BarefootBeast** [comment]
"File at c:\program files (x86)\steam\steamui/css/6.css (previously known as libraryroot.css) not found."
I think this is the issue. I used the remake JS button to get steam to work again, but I couldn't get any of the CS options or JSS options to work again.

Please help, am noob.

**Comment by Jonius7** [comment]
Firstly, you want to go to SteamFriendsPatcher and [change the Library CSS setting to `2.css`](https://imgur.com/a/noQYjlg)
This should fix the tweaks not working at all.

Then `Remake JS`

I've pushed out some small updates that fix the layout (messed up after today's update), but some of the themes are not applying to the sidebar (will look into it)

**Comment by Jonius7** [comment]
See [Release 5.8.6](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.8.6)
