### ISSUE TITLE
Game images are not switching to landscape mode. 

### ISSUE THREAD

**Issue by Rex117** [Jonius7/SteamUI-OldGlory#46]
As the title says, I can't get the images to Landscape mode. The CSS tweaks work to hide the sidebar and the "what's new" tab but the images remain in portrait mode. 

![image](https://user-images.githubusercontent.com/52544680/169703070-d04a34fb-4dc7-462b-8aed-9fa45b223b55.png)

Here are my current settings:

![image](https://user-images.githubusercontent.com/52544680/169703112-e14a1736-c17c-429d-a04b-ce4e6f7fe097.png)

![image](https://user-images.githubusercontent.com/52544680/169703128-f11ba313-81bc-4116-8b0c-5f0c0b1fe1a2.png)

![image](https://user-images.githubusercontent.com/52544680/169703135-0287a9d6-d651-4e0c-82c3-0ee97d361da6.png)

**Comment by Jonius7** [comment]
Landscape Images is currently not compatible with Change Game Image Grid Sizes, try unticking that option.

**Comment by Jonius7** [comment]
Try [Release 5.8.6](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.8.6)
