### ISSUE TITLE
5.8.6 doesn't launch

### ISSUE THREAD

**Issue by AssassinAgent** [Jonius7/SteamUI-OldGlory#52]
5.8.6 old glory installer doesn't launch but gives "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item." error
Launching from zipped or unzipped, as admin or non admin, doesn't matter on which SSD. 
But  5.8.5.1 installer launches with no problems

**Comment by Jonius7** [comment]
That's unusual. Is 5.8.6 getting detected by Antivirus?
