### ISSUE TITLE
Something broke "Box Play Button"

### ISSUE THREAD

**Issue by wordpass1** [Jonius7/SteamUI-OldGlory#53]
Its way too high now, And everything is misplaced. This seems to have just happened today.

![wtfgg](https://user-images.githubusercontent.com/102382867/184065844-705dba0e-b392-499a-8e1d-b13c72e4ab73.PNG)
(The reason it says "Install" is because I reinstalled steam to see if it was a problem with my version.)

**Comment by Jonius7** [comment]
I'm not seeing the Play Box being too high, however the Vertical Nav Bar is definitely too high and will be fixed for the next release.

To change it yourself, the value is in `module_verticalnavbar.scss` under 

`
.appdetailssection_AppDetailsSection_2r4TK.appdetailsprimarylinkssection_LinksSection_3-V8v`
you will find: `transform: translate(5px, -295px) translateY(var(--VerticalNavBarOffset));`
Set it to `transform: translate(5px, -225px) translateY(var(--VerticalNavBarOffset));`


For Play Bar Box I would adjust the value of `top` in `module_verticalnavbar.scss` under
`.appdetailsplaysection_Container_3Yf8b.appdetailsplaysection_InPage_1U7LK`
 current value is: `top: calc(-124px - 3vw);`
