### ISSUE TITLE
Known Issues (5.0-5.8.x)

### ISSUE THREAD

**Issue by Jonius7** [Jonius7/SteamUI-OldGlory#6]
**5 Mar 2022**
Today's Steam Client update has made many of the JS tweaks no longer work. ~~The "JS Tweaks Rework" was supposed to make it easier to update tweaks but is unlikely to be completed at this stage (I am exhausted with programming). JS Tweaks can work again if I can program it to target the file `library.js` (the current version mostly doesn't).~~ Thank you once again for your support.
Fixed with 5.8.x versions

---
**22 Oct 2021**
You may get an error that OldGlory cannot find `5.css` or is not patched, even after downloading the latest [SteamFriendsPatcher](https://github.com/PhantomGamers/SteamFriendsPatcher/releases). This can be ignored, and is fixed in a later version (not yet released)

---

**JS Tweaks won't re-apply unless you go to JS Options and uncheck + check an option**

**Some JS options not working**
Not working since Steam Update 18 May 2021:
  - ~~`CLASSIC Sticky image background`~~
  - `Experimental Don't load HOME game images, only alt text`
  - `Experimental REMOVE GAME PAGE BLOAT`

Please disable the use of them until further notice.

Since 30 Jun 2021 (fixed):
 - ~~`HoverPosition Fix for GameListEntry`~~
  
13 July, 17 Oct (fixed #24):
 - ~~`CLASSIC Sticky image background...`~~ is working again.

- `Increase Number of Screenshots and DLC` Game pages are not showing 12 DLC, only 6. This is due to the particular JS code being moved. When I rework the JS Tweaks, this should be fixed.

---

**Install CSS Tweaks**
- Unchecking `Install CSS Tweaks` doesn't actually disable CSS tweaks.

---

**Using Light UI**
- [Light UI for the Library (by Angelo)](https://github.com/uwuAngelo/LIGHT-UI/tree/main/LIGHT) can be manually installed:
  - copy the `libraryroot.custom.css` file over to `[OldGlory Folder]\themes` and rename it `_light.scss`
  - To change the file extension, they need to not be hidden. [(example in Windows)](https://imgur.com/a/NoBiMvp)

A more automatic method of installing files from Github will be available in a future release.

---

**Using OldGlory GUI (Configurer)**

- After a Clean Install/`Reset`, any options on main page selected requiring JavaScript won't apply on Install. (To be on the safe side).
  - To get JS tweaks, use `Remake JS` option.
  - Go to the `JS options` page and check+uncheck an option.

---

<details><summary> <b>Fixed Issues</b> </summary><br>
<table>
<thead>
<tr>
<th>Fix Date</th>
<th>Issue + Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong><a href="https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/R5.6.5-beta1">5.6.5-beta1</a></strong> - 9 June<br><a href="https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.7.1.1"><strong>Release 5.7.1.1</strong></a> - 30 June</td>
<td>#21 <strong>8 June update</strong> Main issue with patching JS Tweaks</td>
</tr>
<tr>
<td>Fixed in <a href="https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/R5.6.5-beta1">5.6.5-beta1</a></td>
<td>#19 currently occurs when trying to <code>Remake JS</code>. A possible workaround is to change <code>library.js</code> manually (find <code>5:&quot;libraryroot&quot;</code> and change it to <code>5:&quot;libraryreet&quot;</code>)</td>
</tr>
<tr>
<td>Fixed in <a href="https://github.com/Jonius7/SteamUI-OldGlory/commit/996285ac6408a75ff441397b8d70f677bf0cee8d#diff-e5b7184c2784a2cec37ef8fe7bfd963323e6f3cb72fe18c11f6d686b655c7439"><code>996285</code></a><br> the Sidebar Home and Search rework           </td>
<td>When searching with multiple &quot;Advanced Filters&quot;, game list height is not properly set and causes a small black bar at the bottom. Additionally, games may get cut off the bottom of the list.<br/>This is a minor issue that is due to the fixed height set for the game list.</td>
</tr>
<tr>
<td>Use <a href="https://github.com/PhantomGamers/SteamFriendsPatcher/releases">0.1.37-beta or later</a></td>
<td>With the new Steam Update on Dec 22, you will need to select <strong>Steam Beta</strong> in SteamFriendsPatcher&#39;s settings <br/><details><summary>(Screenshot - click to expand)</summary><img src="https://user-images.githubusercontent.com/1049415/103168818-59888680-4882-11eb-936d-d1f5272098ce.png"></img></details></td>
</tr>
<tr>
<td>Fixed in <a href="https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.5.3">Release 5.5.3</a></td>
<td><code>FileExistsError: [WinError 183] Cannot create a file when that file already exists: &#39;scss&#39;</code></td>
</tr>
<tr>
<td>Fixed in <a href="https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.5.3">Release 5.5.3</a></td>
<td>If you are using Steam Beta, replace the <code>fixes.txt</code> file with the one here: (<a href="https://github.com/Jonius7/SteamUI-OldGlory/blob/beta/fixes.txt">https://github.com/Jonius7/SteamUI-OldGlory/blob/beta/fixes.txt</a>)<br>The <code>fixes.txt</code> included is for Steam Stable, and such, the library will not load in Steam Beta (black screen).</td>
</tr>
<tr>
<td>Fixed in <a href="https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.5">Release 5.5</a></td>
<td>Selecting any option in <code>CSS Options</code> <code>What&#39;s New</code> puts it (incorrectly) to the bottom of the page.</td>
</tr>
<tr>
<td>Fixed in <a href="https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.0.1">Release 5.0.1</a></td>
<td>(4 Jan) There seems to be an additional issue, with a clean install, <code>libraryroot.custom.css</code> is not being copied over to the Steam directory properly. #8<br>If your library is already patched, this problem does not seem to occur.</td>
</tr>
</tbody>
</table>
</details>

**Comment by Rex117** [comment]
Hey there, I am having an issue where the Library horizontal game pictures are getting cut-off when reaching the bottom. How or where should I go to fix this?
![steam_library_issue](https://user-images.githubusercontent.com/52544680/109723860-ae939200-7b7c-11eb-9fa6-a2e01605dcad.JPG)

**Comment by Jonius7** [comment]
Ah, yes, the images getting cut off at the bottom, was an issue in an earlier version.

**Comment by snakeeater2703** [comment]
File at c:\program files (x86)\steam\steamui/css/6.css (previously known as libraryroot.css) not found.

**Comment by ST3VI3-RICHI3** [comment]
> File at c:\program files (x86)\steam\steamui/css/6.css (previously known as libraryroot.css) not found.

Same issue for me, the issue started happening after I deleted all css files in my steam library folder, relaunched steam and re-patched them.

**Comment by Jonius7** [comment]
[New Issue for SteamUI-OldGlory versions 5.9+](https://github.com/Jonius7/SteamUI-OldGlory/issues/56)
