### ISSUE TITLE
Library Completely Broke

### ISSUE THREAD

**Issue by Erwbrad** [Jonius7/SteamUI-OldGlory#61]
Hello. After using SFP, my friends menu was broken but the library patches worked, giving me the desired look for my library. But when I tried to unpatch the SFP (my mistake) with the intent on reinstalling it, the whole thing broke. No matter how many times I attempted to re-patch, SFP would stop responding. Attempted to do resets. Nothing worked. What am I supposed to do now?! Here's some logs made by SFP.
[SFP.10.log](https://github.com/Jonius7/SteamUI-OldGlory/files/9528875/SFP.10.log)
[SFP.11.log](https://github.com/Jonius7/SteamUI-OldGlory/files/9528876/SFP.11.log)
[SFP.log](https://github.com/Jonius7/SteamUI-OldGlory/files/9528877/SFP.log)

**Comment by PhantomGamers** [comment]
according to the last log 'c:\program files (x86)\steam\steamui\css' is missing, (re)starting steam should fix it

**Comment by Erwbrad** [comment]
> according to the last log 'c:\program files (x86)\steam\steamui\css' is missing, (re)starting steam should fix it

I attempted doing this multiple times to no avail. I had tried it with steam off, steam on, taskkilled, nothing worked.
