### ISSUE TITLE
While scrolling library it will start flickering badly

### ISSUE THREAD

**Issue by molitar** [Jonius7/SteamUI-OldGlory#62]
Unable to scroll library it starts to flicker really badly.

**Comment by molitar** [comment]
I have tracked it down to   --GridRowGap: I am unable to change this to anything greater than 8px.

It appears when using landscape mode the very bottom row does not want to full display and triggers the flickering. Is there a way to pad the rows so the bottom row does not have a partial cut off view?

**Comment by Jonius7** [comment]
I've been unable to replicate the issue, perhaps it only appears on specific settings
Could you share a screenshot of the JS Options page, thanks.

**Comment by molitar** [comment]
Hello it only happens when using landscape mode. Again it is like the last row is messing up when scrolling to bottom using landscape mode that I had to turn it if.. scroll quickly to bottom as if you are in a hurry to reach the last game and or up and that is when it happens. 
(http://prntscr.com/s759UThWSUcL)

The portrait mode I am using now at the bottom of the page there is plenty of extra room.
http://prntscr.com/aM4yfk8_ohrg

Landscape Mode - when scrolling fast many times back and forth when I hit around this point it will start the screen flicker.
https://imgur.com/WUhoakG

**Comment by Jonius7** [comment]
So I have tested with larger image sizes the last row can get cut off. For that I would try adding a bottom margin:
```
.libraryhomeshowcases_ShowcaseOuter_2tC_c.Focusable {
    margin-bottom: 200px;
}
```

The flickering is something that I have seen happen in the past, though I am unable to replicate now

**Comment by molitar** [comment]
Thanks so I tested today after the update and the variable added.. I noticed no matter how many times I scrolled up and down real fast no flickering.. just have to stop for a bit to see where I am located at for the covers to show.  Much better than all that flickering mess where the only fix was to hit the go to top and start all over.
