### ISSUE TITLE
dont working.

### ISSUE THREAD

**Issue by 0xC0002** [Jonius7/SteamUI-OldGlory#7]
sup, i tried SteamUI OldGlory and it didn't work, i used the friend patcher, checked the steam files and it had worked. but when i floated to install the library theme, steam reloaded and nothing happened. and sorry for my english.

**Comment by PastaDef** [comment]
Make sure to enable "Patch Libary [BETA]" in Steam Friends Patcher settings

![Gitttt](https://user-images.githubusercontent.com/76098286/103164922-949ea180-4811-11eb-9d21-062cd7f78770.PNG)

**Comment by 0xC0002** [comment]
sup, i've managed to tidy up. thanks anyway

**Comment by Jonius7** [comment]
#6 The **Steam Beta** option needs to be ticked (**Patch Library [BETA]** as well, but that should be ticked by default)
