### ISSUE TITLE
Tweaks/themes not applying to my library

### ISSUE THREAD

**Issue by MarcoReckless** [Jonius7/SteamUI-OldGlory#74]
I'm running the **latest Steam stable** (1675222618), **latest SteamFriendsPatcher** (0.0.14) and **latest SteamUI OldGlory** (5.10.6).
This started happening on a recent update (it was working flawlessly before) and I can't seem to figure out what's causing it, my guess is that maybe SFP is patching the wrong .css file since Steam does not seem to refresh itself when applying tweaks with OldGlory.
This is what I tried:

- Patching and un-patching Steam with SteamFriendsPatcher
- Deleting the SteamUI folder
- Toggling different tweaks in SteamUI OldGlory
- Clearing download cache and web browser cache from Steam
- Reinstalling Steam (although without uninstalling it fully first, just overwriting the initial install)
- Switching from stable to beta and back to stable in order to reset some Steam files

![Screenshot_1](https://user-images.githubusercontent.com/13008862/216988870-aabefdf2-2f06-427a-9831-c6cd749acd51.png)

**Comment by Jonius7** [comment]
There is a current issue where if you try to update any `themes` files it will not download them correctly.

Check your `themes` folder, it should look like this. 
![image](https://user-images.githubusercontent.com/1049415/217512072-7b0fc94b-dd41-46e8-abfb-73198c12ed60.png)

**Comment by MarcoReckless** [comment]
Yeah, you're right! For whatever reason it's empty, I imported them back manually and not it works, I will hold on from updating the themes until it's fixed.
