### ISSUE TITLE
Achievements seem to be broken?

### ISSUE THREAD

**Issue by Potato95** [Jonius7/SteamUI-OldGlory#78]
My own achievements aren't being displayed (the section itself seems to be hidden) and friends' appear like this:

![image](https://user-images.githubusercontent.com/46279408/218273312-7cc0004e-8388-413e-be4c-fea8c2f20551.png)

**Comment by Jonius7** [comment]
What does it look like if you disable `_gamepage_activitynews`, guide shown here: https://imgur.com/a/PocNfPE

**Comment by Potato95** [comment]
The issue fixed itself before I did anything, can't replicate it anymore.
