### ISSUE TITLE
UI broken

### ISSUE THREAD

**Issue by HeIsAChar** [Jonius7/SteamUI-OldGlory#8]
Installed Steam Friends Patcher with the "Steam Beta" option and installed the "Vertical Nav Bar" and "Classic layout" options for this thing. Expected to see fixed UI, but this shit appeared instead:
![what](https://user-images.githubusercontent.com/40420649/103481028-0a85a880-4dd0-11eb-9adf-4aad8566eea6.png)

**Comment by Jonius7** [comment]
I have found some issues with copying `libraryroot.custom.css` on a clean install.
Try this build of `old_glory` (replace the .exe)
[SteamUI-OldGlory-5.0.1-Patch.zip](https://github.com/Jonius7/SteamUI-OldGlory/files/5762687/SteamUI-OldGlory-5.0.1-Patch.zip)


If all works well, I'll put out a release later in the day

**Comment by Jonius7** [comment]
Fixed with [5.0.1](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.0.1)
