### ISSUE TITLE
The latest version of the 64-bit exe is triggering Windows Defender

### ISSUE THREAD

**Issue by AtomicTEM** [Jonius7/SteamUI-OldGlory#80]
![image](https://user-images.githubusercontent.com/51938157/219721195-18d0ddf2-b045-4755-8f27-aac17f416cdf.png)

![image](https://user-images.githubusercontent.com/51938157/219721376-43f529fc-c321-49af-b4ba-5131d7d241de.png)

**Comment by Jonius7** [comment]
False positive, it seems Windows Defender is not detecting it anymore.
I released 5.10.7.1 just in case it still is.
