### ISSUE TITLE
Side fade effect game art cutoff too soon

### ISSUE THREAD

**Issue by AtomicTEM** [Jonius7/SteamUI-OldGlory#81]
![image](https://user-images.githubusercontent.com/51938157/220770360-3c841043-f6dc-492f-9100-c52189b3d642.png)
the fade cutsoff to soon

Sidenote, in comparison to vanilla Old Glory cut off game art at the bottom too soon, for example for the Team Fortress 2 game art you are supposed to see the heavy's minigun but you can't with Old Glory.

**Comment by Jonius7** [comment]
Are you wanting the default header size? OldGlory has the header shorter than default

**Comment by TheRealZGYT** [comment]
Might have something to do with margin-bottom being 13px. The white-ish filter doesn't move with the bottom margin and it makes it look that way.


The linked image is how it looks with margin-bottom: 0px which was change with a custom module

![steam_Rr7tOLPSV4](https://user-images.githubusercontent.com/128325561/229477862-5e9138a1-3578-4d25-b286-2b1aaee2ec79.png)


This is the Custom module I'm using to fix it for now, was trying to figure out how to make the hero banner bigger at first but couldn't.

`/* Custom CSS (module 1)
   ========================================================================== */
   
   // Add Custom CSS here (module 1)

.sharedappdetailsheader_TopCapsule_2meE3.sharedappdetailsheader_TopCapsule_2meE3 {
  max-height: 230px;
}

.appdetails_Header_2gZXh.appdetails_HeaderLoaded_tXlLv {
  min-height: 230px;
  margin-bottom: 0px;
}   

/* ========================================================================== 
   END Custom CSS (module 1) */`

**Comment by Jonius7** [comment]
If you want the vanilla behaviour you can also just go into CSS Options -> CSS Secctions and untick `gamepage_header` then Install.
