### ISSUE TITLE
Hiding "You've played for... Would you recommend this?"

### ISSUE THREAD

**Issue by sunlightspectre** [Jonius7/SteamUI-OldGlory#82]
Hello!

I was wondering if it's possible to patch Steam's automated review request.
Generally, I'm an antisocial gamer. I play games to get away from people. c;     
And if I leave a review, I'd rather have it be because a game really meant something to me. Seeing the nag screen makes me less likely to review even things I like, which is the opposite of the intent, probably.

... Anyway, thanks for including an alternative to SFP. I have a Windows 8.1 box I use for old games that Win10/11 and especially Proton don't virtualise well, and seeing SFP claim that they don't make updates for 'stubborn' users, when the entire point of SFP being a stubborn reaction against Valve's design is - a bit hypocritical.

**Comment by Jonius7** [comment]
It's certainly very simple to hide the "You've Played for X hours" notification. The problem I have is I don't have one for any of my games so I can't grab the right CSS class to target.

You could try having a look in -dev mode yourself and selecting the notification to see what it's called? My video guide should tell you how to do so: https://youtu.be/7_3e9j8FFv8?t=645

> ... Anyway, thanks for including an alternative to SFP. I have a Windows 8.1 box I use for old games that Win10/11 and especially Proton don't virtualise well, and seeing SFP claim that they don't make updates for 'stubborn' users, when the entire point of SFP being a stubborn reaction against Valve's design is - a bit hypocritical.

No problem. OldGlory should be compatible with Windows 7 and up for the foreseeable future (using Python 3.8)

**Comment by sunlightspectre** [comment]
Wonderful; that should take care of it just fine! I'll mark this as closed, but thanks for the quick assist, and support..!

**Comment by Jonius7** [comment]
Oops, turns out I have already added the feature to toggle off the **"You've Played for X hours"** notification. In `variables.css` under `--RecommendGame` set it to `none`

**Comment by sunlightspectre** [comment]
Hello again, just checking in to thank you - and mention, would it be possible to add a fix to disable (or at least hide) the library developer broadcasts? They take up an incredible amount of space, and previous fixes - disabling the webkit.css - only seem to decrease the size, rather than hide the broadcasts.

Regardless, thank you beyond thanks for keeping steam usable. It's a chore, but those of us who are grateful, are exceptionally grateful.

**Comment by Jonius7** [comment]
OldGlory does reduce the developer broadcasts widith to `50%` but if you would like to hide them completely:

```css
.appdetailssection_Body_5uvIN.appdetailsbroadcastsection_Body_CFp7F {
    display: none;
}
.appdetailsbroadcastsection_BroadcastBox_9nwsC {
    display: none;
}
```

should do it.

**Comment by sunlightspectre** [comment]
Thanks a million. Just for the purposes of clarifying for anyone stumbling in from a search query, the above should be added to steamoldglory -> scss ->_gamepagebroadcasts, replacing the prior settings. I figure anyone looking here _probably_ already knows that, but it never hurts to add extra, given the amount of time I've stumbled on 'thanks; fixed' with no explanation, grumble...

And to you, @Jonius7 , thanks as ever for the quick save..! 🥂
