### ISSUE TITLE
Steam Beta Update March 28 Broke JS 

### ISSUE THREAD

**Issue by Eerorri** [Jonius7/SteamUI-OldGlory#85]
![image](https://user-images.githubusercontent.com/97610612/228332957-673e4468-80b0-45b7-8bfb-627eec0c75f7.png)

When applying the JS the steam windows goes black, cant access normal library or downloads, unless disabling the beta and applying again

**Comment by Jonius7** [comment]
Looks like the update did break and change some things. Having a look.

**Comment by Jonius7** [comment]
I have put out a new pre-release that fixes the black screen issue as well as fix some other JS tweaks as well.
https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/R5.11.2-pre1
