### ISSUE TITLE
CSS doesn't install?

### ISSUE THREAD

**Issue by DatGamerYoloYT** [Jonius7/SteamUI-OldGlory#87]
For some reason the CSS tweaks don't install and just stop at writing the new libraryroot.custom.css
Here's a image for no reason probably:
![image](https://user-images.githubusercontent.com/84749503/230478571-a6b1ab6e-ccf9-4f51-b61c-8cbe8b2ff130.png)

**Comment by Jonius7** [comment]
`Install CSS Tweaks` is unticked? Or was that you trying different options?

**Comment by DatGamerYoloYT** [comment]
> `Install CSS Tweaks` is unticked? Or was that you trying different options? Additionally `5.11.2-pre1` is for Steam Beta only, if using Steam Stable use `5.11.1`.

where is install css tweaks
also im using steam beta

**Comment by Jonius7** [comment]
The first checkbox.
You are using [SFP](https://github.com/PhantomGamers/SFP) or the `Patch CSS` option to apply CSS beforehand, yes?sf

**Comment by DatGamerYoloYT** [comment]
> The first checkbox. You are using [SFP](https://github.com/PhantomGamers/SFP) or the `Patch CSS` option to apply CSS beforehand, yes?

yes

**Comment by molitar** [comment]
Thanks the pre-release fixed it for myself too.
