### ISSUE TITLE
Need some help hiding the Achievements section

### ISSUE THREAD

**Issue by Fizzboks** [Jonius7/SteamUI-OldGlory#92]
Hello.
I am trying to hide some sections on Steam and I managed to hide almost all of the ones I wanted to, except for the Achievements section. I followed your guidance on using the dev mode to highlight the section and change the appropriate CSS, but I wasn't able to find the code to put display: none to. I am not familiar with programming in general so I was hoping to turn to you for advice. Thank you making this awesome tool, my experience on Steam would not be nearly as pleasant without it.

**Comment by sunlightspectre** [comment]
I _believe_ off the top of my head that if you open up:

- SteamUI-Oldglory - >

- CSS Options - >

- CSS Sections - > (It's the top right!)

- achievements_page (disable this!)

That should hide achievements without need for hand-editing. I can't test right now, sorry!

**Comment by sunlightspectre** [comment]
Hrmn... 

I think I was a dummy, that just tells OldGlory not to import the separate achievements.css rather then exclude it entirely.    
Apologies, juggling a bit today. Re-check that box, and let me mess around for a bit...

It looks like none of the settings currently available effect achievement visibility. Aggravating. I'll do my best to figure something out this weekend.

**Comment by sunlightspectre** [comment]
@Fizzboks I've tried every permutation of achievements_container I can find, and steam just doesn't want to hide the achievements segment. Unless there's something I'm missing that @Jonius7 knows about, I'm afraid you're stuck with them. I'm very sorry, and wish I had better news for you.

**Comment by Jonius7** [comment]
This should work for most if not all pages, since the Achievements section is usually div no.4

```css
.appdetailsoverview_SeekTarget_vzLed:nth-of-type(4) {
    display: none;
}
```
