### ISSUE TITLE
Make the default changes easily disabled

### ISSUE THREAD

**Issue by FatheredPuma81** [Jonius7/SteamUI-OldGlory#93]
The user shouldn't have to go and uncheck random boxes under CSS Sections just to get their friends and download button back to the normal location.
Edit 2: Okay I managed to finally fix it by deleting my entire OldGlory install, opening a fresh install, Unchecking Install CSS Tweaks, made sure custom_modules1/2 were unchecked, and then pressed Reload Config.

Edit 3: Rewrote this after cooling down. Hidden changes piss me off.

**Comment by Jonius7** [comment]
That is my bad, the CSS for the bottom top bar should be disabled by default now
