### ISSUE TITLE
UI is buggy

### ISSUE THREAD

**Issue by BigtornG** [Jonius7/SteamUI-OldGlory#96]
Whenever I install the skin and teaks I want from Old Glory, It keeps bugging out.

https://gyazo.com/05cb2329483b00450a69f931a42cda71

**Comment by sunlightspectre** [comment]
Question, did you:

Cogwheel (Lower Right) -> Remake JS
Advanced Options ->Patch CSS
Install 

If you've used OldGlory in the past, sometimes you've got to start from the beginning in that order.
As a side note, what did you do to get that classical-looking layout, it's very nice?  
I'm not asking for those reasons, though, I can test it and see if there's anything I'm missing.

**Comment by BigtornG** [comment]
these are my settings
https://gyazo.com/04018c4fcff0dfe9448cdb71eb212891

this is what happen when I pressed Remake Js
https://gyazo.com/c1bd4d294d8bd5716997b00c4064e6fe

**Comment by BigtornG** [comment]
yea I did all the buttons in order and nothing happen

**Comment by Jonius7** [comment]
What happens if you use SFP and restart Steam?

**Comment by BigtornG** [comment]
SFP doesn't work for me right now

I get this error
https://gyazo.com/9a6804f0d3c10e3023467b7dcf7c13f8

**Comment by BigtornG** [comment]
ok i had to download a older version of SFP  0.0.14
