### ISSUE TITLE
CSS and themes do not apply

### ISSUE THREAD

**Issue by Brendini** [Jonius7/SteamUI-OldGlory#99]
When go to install the CSS tweaks and Theme, nothing changes
![3](https://github.com/Jonius7/SteamUI-OldGlory/assets/38304412/fea72d6f-7537-4d04-879a-03abab6d8712)
![2](https://github.com/Jonius7/SteamUI-OldGlory/assets/38304412/6ac2218f-52f9-48e0-96c8-86286575dba3)
![1](https://github.com/Jonius7/SteamUI-OldGlory/assets/38304412/9831aadc-d04d-4f23-980b-53579d85e2eb)

**Comment by PhantomGamers** [comment]
Did you click `Patch CSS` in advanced options?

**Comment by Brendini** [comment]
that worked, thanks for the help
